apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdpdeploy
  labels:
     app: durgadeploy
spec:     
  replicas: 2
  selector: 
    matchLabels: 
      app: durgadeploy
  template:
    metadata:
      labels:
        app: durgadeploy
    spec:
      containers:
      - name: myc2
        image: nginx
        ports:
        - containerPort: 8080