apiVersion: v1
kind: ReplicationController 
metadata:
  name: durgarc
spec:
  replicas: 3
  selector:
    app: durgaapp
  templates:
    metadata:
      labels:
        app: durgaapp
    spec:
      containers: 
      - name: myc11
        image: nginx
        ports:
        - containerPort: 8080

   