apiVersion: v1
kind: ReplicationController 
metadata:
  name: durgarc
spec:
  replicas: 2
  selector:
    app: durgaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: durgaapp
        version: 2.6.1
    spec:
      containers: 
      - name: myc11
        image: nginx
        ports:
        - containerPort: 8080

   