apiVersion: v1
kind: Service
metadata:
  name: durgasvc
  labels:
    app: durgaapp 
    version: 2.6.1
spec:
  type: Nodeport
  ports:
  - port: 8080    
    nodeport: 30001
    protocol: TCP
  selector:
    app: durgaapp 
    version: 2.6.1
    